language: python
matrix:
  include:
  - python: 2.7
    env: PACKAGES=common hub wsgi
  - python: 3.6
    env: PACKAGES=common hub
install: ./.travis-dev-setup.sh $PACKAGES
script: ./.travis-run-tests.sh $PACKAGES
notifications:
    email: false
    irc:
        - "irc.freenode.net#moksha"
    on_success: change
    on_failure: change
